Martins feeble updates

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,8 +5,8 @@ name: CI
     types: [opened, synchronize, reopened, edited, ready_for_review]
 
 jobs:
-  sanity-check:
-    name: Sanity Check
+  chart-certification:
+    name: Chart Certification
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout
@@ -82,12 +82,6 @@ jobs:
           echo "The 'Sanity Check PR Content' step has failed."
           exit 1
 
-  build-and-verify:
-    name: Build and Verify
-    needs:
-      - sanity-check
-    runs-on: ubuntu-20.04
-    steps:
       - name: 'Remove label from PR'
         uses: actions/github-script@v3
         continue-on-error: true
@@ -108,12 +102,7 @@ jobs:
           ref: ${{ github.event.pull_request.head.ref }}
           repository: ${{ github.event.pull_request.head.repo.full_name }}
 
-      - name: Set up Python 3.x
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.9'
-
-      - name: Verify PR
+      - name: 'Verify PR'
         id: verify_pr
         run: |
           gpg --version
@@ -177,61 +166,45 @@ jobs:
                 labels: ['authorized-request']
             })};
 
-  approve-and-merge-pr:
-    needs:
-      - build-and-verify
-    runs-on: ubuntu-latest
-    name: Approve and Merge PR
-    steps:
+      - name: 'Approve PR'
+        id: approve_pr
+        if: ${{ steps.verify_pr.conclusion == 'success' }}
+        uses: hmarr/auto-approve-action@v2
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
 
-    - uses: hmarr/auto-approve-action@v2
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
+      - name: 'Merge PR'
+        id: merge_pr
+        if: ${{ steps.approve_pr.conclusion == 'success' }}
+        uses: pascalgn/automerge-action@v0.13.1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          MERGE_METHOD: squash
+          MERGE_LABELS: ""
 
-    - uses: pascalgn/automerge-action@v0.13.1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        MERGE_METHOD: squash
-        MERGE_LABELS: ""
+      - if: ${{ steps.merge_pr.conclusion == 'failure' }}
+        run: |
+          echo "The 'PR has not been merged' a step has failed."
+          exit 1
 
-  release-charts:
-    needs:
-      - approve-and-merge-pr
-    runs-on: ubuntu-20.04
-    steps:
       - name: Block until there is no running workflow
         uses: softprops/turnstyle@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: Checkout
-        uses: actions/checkout@v2
-        with:
-          ref: ${{ github.event.pull_request.head.ref }}
-          repository: ${{ github.event.pull_request.head.repo.full_name }}
-          fetch-depth: 0
-
-      - name: Configure Git
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
-
-      - name: Set up Python 3.x
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.9'
 
       - name: Release Charts
         env:
           GITHUB_REF: ${{ github.ref }}
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+          REPORT_CONTENT: ${{steps.verify_pr.report-content}}
         id: release-charts
         run: |
+          echo ${{steps.verify_pr.report-content}}
           curl -L -o cr.tar.gz https://github.com/helm/chart-releaser/releases/download/v1.2.0/chart-releaser_1.2.0_linux_amd64.tar.gz
           tar zxvf cr.tar.gz
           sudo cp -f cr /usr/local/bin/cr
           python3 -m venv ve1
           cd scripts && ../ve1/bin/pip3 install -r requirements.txt && cd ..
-          docker pull quay.io/redhat-certification/chart-verifier:latest
           curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
           cd scripts && ../ve1/bin/python3 setup.py install && cd ..
           INDEX_BRANCH=$(if [ "${GITHUB_REF}" = "refs/heads/main" ]; then echo "refs/heads/gh-pages"; else echo "${GITHUB_REF}-gh-pages"; fi)
